language: node_js
node_js:
- '0.10'
before_install:
- npm install -g grunt-cli bower
- bower install
env:
  global:
  - secure: F9nJwnwg5jDnS/RsFIijyxhnjIFAV8MyRppYAjLKwz7ofP+kKmEvAuZvfrua91yJfLsAM8R924oGz36Y0VF46K9tg1ViNUTGN0AvIWHWL8gDYmdSSwU1PjU0vah2/D91U6UOKPUn46lzM93rb9KUjFpllicO0xJqgI4/Vq3E/1s=
  - secure: V3vIcl2Oq59U3WIjtvgoB2pKe+3uhrjcIMqVZe5vBpreAfyYQH9OtqLO5pTKs+Wx3nPaZSyv6dsbwUXcrJCBTPd7elJi7RgN57S7yrDOCgcoZ2C7YImH8D/oDMsjecu+RdkjeETht8X5cPEg0THNGhYRz8H/gSvjkxMNUhkcIUA=
